import VersionCommand from "./commands/System/ver";
import DirectoryCommand from "./commands/Filesystem/dir";
import ChangeDirectoryCommand from "./commands/Filesystem/cd";
import ClearCommand from "./commands/System/cls";
import CreditsCommand from "./commands/General/credits";
import GithubCommand from "./commands/General/github";
import DateCommand from "./commands/General/date";
import TimeCommand from "./commands/General/time";
import WwwCommand from "./commands/General/www";
import ConfettiCommand from "./commands/General/confetti";
import EchoCommand from "./commands/Utility/echo";
import IpCommand from "./commands/Utility/ip";
import GeoIpCommand from "./commands/Utility/geoip";
import WaitCommand from "./commands/System/wait";
import HttpcatCommand from "./commands/General/httpcat";
import HttpdogCommand from "./commands/General/httpdog";
import MakeDirectoryCommand from "./commands/Filesystem/mkdir";
import CatCommand from "./commands/Filesystem/cat";
import ECodeAPICommand from "./commands/ECodeAPI/ecode";
import GeoCommand from "./commands/Utility/geo";
import RegisterCmdCommand from "./commands/System/registercommand";
import CommandCOMCommand from "./commands/System/command";
import DeleteCommand from "./commands/Filesystem/rm";
import DeleteDirectoryCommand from "./commands/Filesystem/rmdir";
import WeatherCommand from "./commands/Utility/weather";
import StatusCommand from "./commands/System/status";
import AboutmeCommand from "./commands/Utility/aboutme";
import DownloadCommand from "./commands/Filesystem/download";
import UploadCommand from "./commands/Filesystem/upload";
import RenameCommand from "./commands/Filesystem/rename";
import CopyCommand from "./commands/Filesystem/copy";
import MoveCommand from "./commands/Filesystem/move";
import TreeCommand from "./commands/Filesystem/tree";
import XCopyCommand from "./commands/Filesystem/xcopy";
import AttribCommand from "./commands/Filesystem/attrib";
import FindCommand from "./commands/Filesystem/find";
import FindStrCommand from "./commands/Filesystem/findstr";
import FCCommand from "./commands/Filesystem/fc";
import ChkDskCommand from "./commands/Filesystem/chkdsk";
import MatrixCommand from "./commands/General/matrix";
import RebootCommand from "./commands/System/reboot";
import PasswordCommand from "./commands/Utility/password";
import Base64Command from "./commands/Utility/base64";
import MoreCommand from "./commands/Utility/more";
import SortCommand from "./commands/Utility/sort";
import IpConfigCommand from "./commands/Utility/ipconfig";
import NetStatCommand from "./commands/Utility/netstat";
import PingCommand from "./commands/Utility/ping";
import TraceRouteCommand from "./commands/Utility/traceroute";
import CalendarCommand from "./commands/Utility/calendar";
import CalcCommand from "./commands/Utility/calc";
import NotesCommand from "./commands/Utility/notes";
import NcCommand from "./commands/Apps/nc";
import PaintCommand from "./commands/Apps/paint";
import PlayerCommand from "./commands/Apps/player";
import EditCommand from "./commands/Apps/edit";
import ListCommand from "./commands/Apps/list";
import SnakeCommand from "./commands/Apps/snake";
import TetrisCommand from "./commands/Apps/tetris";
import TelnetCommand from "./commands/Apps/telnet";
import AnsiDemoCommand from "./commands/Apps/ansidemo";
import QBCommand from "./commands/Apps/qb";
import DebugCommand from "./commands/Apps/debug";
import JsCommand from "./commands/Apps/js";
import FullscreenCommand from "./commands/System/fullscreen";
import MemCommand from "./commands/System/mem";
import SetCommand from "./commands/System/set";
import PathCommand from "./commands/System/path";
import PromptCommand from "./commands/System/prompt";
import DosKeyCommand from "./commands/System/doskey";
import ModeCommand from "./commands/System/mode";

export const registerAllCommands = () => {
  let registeredCommands = {};

  // System commands
  registeredCommands['ver'] = new VersionCommand();
  registeredCommands['cls'] = new ClearCommand();
  registeredCommands['wait'] = new WaitCommand();
  registeredCommands['registercommand'] = new RegisterCmdCommand();
  registeredCommands['command'] = new CommandCOMCommand();
  registeredCommands['status'] = new StatusCommand();
  registeredCommands['reboot'] = new RebootCommand();
  registeredCommands['fullscreen'] = new FullscreenCommand();
  registeredCommands['mem'] = new MemCommand();
  registeredCommands['set'] = new SetCommand();
  registeredCommands['path'] = new PathCommand();
  registeredCommands['prompt'] = new PromptCommand();
  registeredCommands['doskey'] = new DosKeyCommand();
  registeredCommands['mode'] = new ModeCommand();

  // Filesystem commands
  registeredCommands['dir'] = new DirectoryCommand();
  registeredCommands['cd'] = new ChangeDirectoryCommand();
  registeredCommands['mkdir'] = new MakeDirectoryCommand();
  registeredCommands['type'] = new CatCommand();
  registeredCommands['del'] = new DeleteCommand();
  registeredCommands['rmdir'] = new DeleteDirectoryCommand();
  registeredCommands['download'] = new DownloadCommand();
  registeredCommands['upload'] = new UploadCommand();
  registeredCommands['rename'] = new RenameCommand();
  registeredCommands['copy'] = new CopyCommand();
  registeredCommands['move'] = new MoveCommand();
  registeredCommands['tree'] = new TreeCommand();
  registeredCommands['xcopy'] = new XCopyCommand();
  registeredCommands['attrib'] = new AttribCommand();
  registeredCommands['find'] = new FindCommand();
  registeredCommands['findstr'] = new FindStrCommand();
  registeredCommands['fc'] = new FCCommand();
  registeredCommands['chkdsk'] = new ChkDskCommand();

  // General commands
  registeredCommands['credits'] = new CreditsCommand();
  registeredCommands['github'] = new GithubCommand();
  registeredCommands['date'] = new DateCommand();
  registeredCommands['time'] = new TimeCommand();
  registeredCommands['www'] = new WwwCommand();
  registeredCommands['confetti'] = new ConfettiCommand();
  registeredCommands['httpcat'] = new HttpcatCommand();
  registeredCommands['httpdog'] = new HttpdogCommand();
  registeredCommands['matrix'] = new MatrixCommand();

  // Utility commands
  registeredCommands['echo'] = new EchoCommand();
  registeredCommands['ip'] = new IpCommand();
  registeredCommands['geoip'] = new GeoIpCommand();
  registeredCommands['geo'] = new GeoCommand();
  registeredCommands['aboutme'] = new AboutmeCommand();
  registeredCommands['weather'] = new WeatherCommand();
  registeredCommands['password'] = new PasswordCommand();
  registeredCommands['base64'] = new Base64Command();
  registeredCommands['more'] = new MoreCommand();
  registeredCommands['sort'] = new SortCommand();
  registeredCommands['ipconfig'] = new IpConfigCommand();
  registeredCommands['netstat'] = new NetStatCommand();
  registeredCommands['ping'] = new PingCommand();
  registeredCommands['traceroute'] = new TraceRouteCommand();
  registeredCommands['calendar'] = new CalendarCommand();
  registeredCommands['calc'] = new CalcCommand();
  registeredCommands['notes'] = new NotesCommand();

  // ECodeAPI
  registeredCommands['ecode'] = new ECodeAPICommand();

  // TUI Applications
  registeredCommands['nc'] = new NcCommand();
  registeredCommands['paint'] = new PaintCommand();
  registeredCommands['player'] = new PlayerCommand();
  registeredCommands['edit'] = new EditCommand();
  registeredCommands['list'] = new ListCommand();
  registeredCommands['snake'] = new SnakeCommand();
  registeredCommands['tetris'] = new TetrisCommand();
  registeredCommands['telnet'] = new TelnetCommand();
  registeredCommands['ansidemo'] = new AnsiDemoCommand();
  registeredCommands['qb'] = new QBCommand();
  registeredCommands['debug'] = new DebugCommand();
  registeredCommands['js'] = new JsCommand();

  return registeredCommands;
};