name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run : npm i
      shell: bash
    - run : npm ci
      shell: bash
    - run : npm run build
      shell: bash
